### ISSUE TITLE
State

### ISSUE THREAD

**Issue by Mgblugs** [dehsgr/node-red-contrib-meross#11]
Ok. Thanks for this. I have the MSS310.  Can it be polled for current power usage info?

**Comment by dehsgr** [comment]
Sorry. This is currently not planned. Feel free to contribute to this project.

**Comment by Mgblugs** [comment]
Honestly, any previous coding I've done with this stuff has all been copy/paste exercises and minimum edits.
Please help! 
This is, I believe what I want to poll.
![image](https://user-images.githubusercontent.com/25230539/129080609-c399c24f-1167-4c36-a981-27cecaf20f4a.png)

**Comment by dehsgr** [comment]
Maybe you could provide additional info (like app screen shot, …). So I may see what I can do for you. I don‘t have such device. So I would have to implement this „on blue haze“…

**Comment by Mgblugs** [comment]
These were taken at the same time for ease.

![image](https://user-images.githubusercontent.com/25230539/129082364-99b6d6f8-9e92-4fc3-9e84-262cd53146b3.png)

![1628706438826](https://user-images.githubusercontent.com/25230539/129083432-affdd0ca-9c62-44a6-9304-d6fc9abad054.jpg)

**Comment by dehsgr** [comment]
@Mgblugs I would like to tryout current source code (you have to replace your _meross/smartplug-control.js_ file). After sending the following payload...
`{
  "namespace": "Appliance.Control.Electricity"
}`
...you should receive the electricity section from the screen shot you sent to me. Can you confirm this?

If positive: I'll publish a new package version soon.
If negative: Please give me some more information and screen shots what's working and what's not working and errors, you receive.

Thanks!

**Comment by Mgblugs** [comment]
Just to be clear, I replace the code in my current smartplug-control.js file with the modified code you have published here?

**Comment by dehsgr** [comment]
Yes

**Comment by Mgblugs** [comment]
This has happened twice now. my installation is on a windows pc. 
After modifying the code (using notepad++), I get this:

![image](https://user-images.githubusercontent.com/25230539/131030290-75773a7d-120d-433e-9f42-831d692ef239.png)
![image](https://user-images.githubusercontent.com/25230539/131030393-3fb4f965-4084-4430-a6cc-82e41719878e.png)

**Comment by dehsgr** [comment]
@Mgblugs why didn't you override the whole file _meross/smartplug-control.js_ as described? I would like you to do things as described. Otherwise it would be too complicated to get things flying here...

**Comment by Mgblugs** [comment]
Okay okay! 
I am away until tomorrow. Will retry then.
Thanks

**Comment by Mgblugs** [comment]
@dehsgr Like this? You can see the debug.
![image](https://user-images.githubusercontent.com/25230539/131250335-b7c24710-c5a7-4f53-8c34-32a924a0c211.png)

**Comment by dehsgr** [comment]
@Mgblugs no, as described in my message before 3 days. You should send a JSON Object Payload. 🤓

`{ "namespace": "Appliance.Control.Electricity" }`

**Comment by Mgblugs** [comment]
![image](https://user-images.githubusercontent.com/25230539/131251414-5b3b10af-ae41-4d02-af2f-458503fc54ae.png)

**Comment by dehsgr** [comment]
@Mgblugs okay, I found sth. wrong. Please try to **replace _smartcontrol.js_ again** and give feedback.

**Comment by Mgblugs** [comment]
Success!

![image](https://user-images.githubusercontent.com/25230539/131252751-af496dac-7e72-4a85-b74b-49ae74218075.png)
Now I need to figure out the equations! 
Thanks a lot!

**Comment by dehsgr** [comment]
@Mgblugs sorry. I had to re-commit bugfix. :-(

**Comment by Mgblugs** [comment]
What does that mean?

**Comment by dehsgr** [comment]
@Mgblugs I committed files in a bad structure. It is repository-specific. Thanks for your feedback. I‘ll publish new version to NPM later this day…

**Comment by dehsgr** [comment]
Published new version to NPM.

**Comment by Mgblugs** [comment]
Don't mean to be a pest but do you have to do something to deploy this update as a flow?
It still shows as 1.3.1

![image](https://user-images.githubusercontent.com/25230539/132399333-fac86006-b9b5-4358-9ff0-be02334c93c3.png)


TIA

**Comment by dehsgr** [comment]
Should be updated now.

**Comment by Varguit** [comment]
@dehsgr Thanks for this contribution, I was looking for how to get the power values for my meross plug.
You should reflect this option on the main page, or in the example flow.

> @Mgblugs no, as described in my message before 3 days. You should send a JSON Object Payload. 🤓
> 
> `{ "namespace": "Appliance.Control.Electricity" }`

**Comment by dehsgr** [comment]
@Varguit this is already documented in the ReadMe?!
