### ISSUE TITLE
Error: 'Reveiced unexpected Data'

### ISSUE THREAD

**Issue by cajoma** [dehsgr/node-red-contrib-meross#3]
Dear dehsgr.

I found in Fiddler the following Timestamp and Token (sign) - Thanks for your hint!!
![image](https://user-images.githubusercontent.com/76684729/103270458-3f50c480-49b8-11eb-9ae9-71a83442ceda.png)

If I filled out the data (s. beyond:) It comes up with an Error: 'Reveiced unexpected Data'
![image](https://user-images.githubusercontent.com/76684729/103270531-6d360900-49b8-11eb-8595-6c0760ea0313.png)
![image](https://user-images.githubusercontent.com/76684729/103270540-732bea00-49b8-11eb-9bc1-da266fb3727c.png)

My Code is:
![image](https://user-images.githubusercontent.com/76684729/103270590-9191e580-49b8-11eb-9a62-53fc6e5f0de0.png)

![image](https://user-images.githubusercontent.com/76684729/103270779-0ebd5a80-49b9-11eb-9b44-07c7479a66a4.png)

If I watch the network with Fiddler, it looks like there comes no protocol into the network.
What is my mistake?

Thanks for your support.

**Comment by dehsgr** [comment]
Ouch. My fault! I corrected my answer in issue #2. You should use **request body** instead of response body for getting correct information. ;-)

I would like you to confirm it is now working for you, before I close this request.

**Comment by cajoma** [comment]
Unfortunately it is still the same behavior:

![image](https://user-images.githubusercontent.com/76684729/103274315-a9ba3280-49c1-11eb-83cd-e1423cb64f51.png)
![image](https://user-images.githubusercontent.com/76684729/103274322-b179d700-49c1-11eb-922b-9ef27ab878ad.png)

**Comment by dehsgr** [comment]
I published an update to v1.0.2. Please check with that update and fill in new sniffed data including message id there. Thank you again for your feedback!

**Comment by peterchs** [comment]
I also had issues but had ended up just hacking smartplug-control.js until it worked, copying from the sniffed ios payload.   Presumably it was the messageId that I'd fixed.  Meant to raise an issue but didnt get round to it..

Anyway updated to 1.0.2, filled in the message id in config and its now working without the hacks.

Thanks for this & thanks for the module.
